[package]
name = "yuv-sys"
version = "0.2.0"
edition = "2021"
authors = ["Theo Monnom <theo.8bits@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "libyuv bindings"

[build-dependencies]
bindgen = "0.69"
cc = "1.0"
