[package]
name = "mikado"
version = "0.1.0"
edition = "2021"
authors = ["Theo Monnom <theo.8bits@gmail.com>"]
build = "build/main.rs"

[features]
dsp = []

[dependencies]
log = "0.4"
thiserror = "1"
bitflags = "2.4.1"
rustfft = "6.1.0"

[build-dependencies]
bindgen = "0.66.1"
cc = "1.0.79"
